server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dugu?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    #?????????
    mybatis.configuration.cache-enabled : true
    #???,???????????????
    mybatis.configuration.lazy-loading-enabled : false
    #??????(?????SQL??),????????????,?????
    mybatis.configuration.aggressive-lazy-loading : false
    #??????????????????
    mybatis.configuration.multiple-result-sets-enabled : true
    #??????????SQL?????
    mybatis.configuration.default-executor-type : REUSE
    #?????????
    mybatis.configuration.default-statement-timeout : 25000
    #???????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

